apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-ctr
    image: dotnetderek/node-web-app:v1
    ports:
    - containerPort: 8080
